# Generated by Django 3.0.3 on 2020-03-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('importent', models.CharField(choices=[('1', '不重要不紧急'), ('2', '重要不紧急'), ('3', '不重要但紧急'), ('4', '重要且紧急')], max_length=10)),
                ('finish', models.CharField(choices=[('doing', '进行中'), ('done', '已完成')], max_length=10)),
            ],
        ),
    ]
