# Generated by Django 3.0.3 on 2020-03-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200318_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='class_type',
            field=models.CharField(default='success', max_length=50),
        ),
        migrations.AlterField(
            model_name='todo',
            name='finish',
            field=models.CharField(choices=[('doing', '进行中'), ('done', '已完成')], default='doing', max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='important',
            field=models.CharField(choices=[('1', '不重要不紧急'), ('2', '重要不紧急'), ('3', '不重要但紧急'), ('4', '重要且紧急')], default='4', max_length=10),
        ),
    ]
