# Generated by Django 3.0.3 on 2020-03-18 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='HELLO WANG', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Col',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='列表1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='footer1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('col', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteinfo.Col')),
            ],
        ),
        migrations.AddField(
            model_name='col',
            name='footer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteinfo.Footer'),
        ),
    ]
